# DESCARGAR LA IMAGEN QUE QUEREMOS UTILIZAR 
FROM node:22

# LABEL developer="Alejandro"

# DEFINIR EL DIRECTORIO DE LA APLICACION
WORKDIR /app

# COPIAR LOS FICHEROS CON LA INFORMACION DE LAS DEPENDENCIAS
COPY package*.json ./

# OBTENER LOS MODULOS (DEPENDENCIAS)
RUN npm install

# COPIAR TODO EL PROYECTO
COPY . . 

# ARRANCAR LA APLICACION
# CMD ["node", "src/index.ejs"]
CMD ["npm", "start"]